"""Initial migration

Revision ID: 001
Revises: 
Create Date: 2023-10-10 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('zoho_access_token', sa.String(length=200), nullable=True),
    sa.Column('zoho_refresh_token', sa.String(length=200), nullable=True),
    sa.Column('todoist_access_token', sa.String(length=200), nullable=True),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), nullable=True),
    sa.Column('email_confirmation_token', sa.String(length=200), nullable=True),
    sa.Column('zoho_token_expiry', sa.DateTime(), nullable=True),
    sa.Column('selected_zoho_portal', sa.String(length=200), nullable=True),
    sa.Column('sync_direction', sa.String(length=20), nullable=True),
    sa.Column('sync_frequency', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
